github
Signed-off-by: weizhoublue <weizhou.lan@daocloud.io>

diff --git a/.github/workflows/lint-golang.yaml b/.github/workflows/lint-golang.yaml
--- a/.github/workflows/lint-golang.yaml
+++ b/.github/workflows/lint-golang.yaml
@@ -84,7 +84,7 @@ jobs:
       - name: Install Go
         uses: actions/setup-go@v4
         with:
-          go-version: 1.23.1
+          go-version: 1.23.4
 
       - name: Checkout code
         uses: actions/checkout@v3
@@ -106,7 +106,7 @@ jobs:
       - name: Install Go
         uses: actions/setup-go@v4
         with:
-          go-version: 1.23.1
+          go-version: 1.23.4
 
       - name: Checkout code
         uses: actions/checkout@v3
@@ -116,7 +116,6 @@ jobs:
 
       - name: Check module vendoring
         run: |
-          go vet ./... || {echo "go vet failed"; exit 1}
           go mod tidy
           go mod vendor
           if ! test -z "$(git status --porcelain)"; then
@@ -126,7 +125,7 @@ jobs:
 
       - name: Check build
         run: |
-          go vet ./... || {echo "go vet failed"; exit 1}
+          go vet ./... || {echo "go vet failed"; exit 1 ; }
           make build-binaries || {echo "make build-binaries failed"; exit 1}
 
       # ================ lint
@@ -149,7 +148,7 @@ jobs:
   #     - name: Install Go
   #       uses: actions/setup-go@v4
   #       with:
-  #         go-version: 1.23.1
+  #         go-version: 1.23.4
 
   #     - name: Checkout code
   #       uses: actions/checkout@v3
